esphome:
  name: tcl-ac
  includes:
    - tcl-ac.h

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.101.240
    gateway: 192.168.101.1
    subnet: 255.255.255.0
  ap:
    ssid: AC Hotspot
    password: !secret hotspot_pass

api:
  password: !secret api_pass

ota:
  - platform: esphome
    password: !secret ota_pass

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  parity: EVEN

logger:
    level: DEBUG
    baud_rate: 0

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new MyCustomClimate(id(uart_bus));
    App.register_component(my_custom_climate);
    return {my_custom_climate};

  climates:
    - name: "TCL a/c"
      id: my_custom_climate

select:
  - platform: template
    name: Vertical swing
    id: vswing
    entity_category: config
    options:
      - "Last position"
      - "Fix top"
      - "Fix upper"
      - "Fix mid"
      - "Fix lower"
      - "Fix bottom"
      - "Move full"
      - "Move upper"
      - "Move lower"
    set_action:
      then:
        lambda: |-
          static_cast<MyCustomClimate*>(id(my_custom_climate))->control_vertical_swing(x);
 
web_server:
  port: 80

captive_portal:
